name: Apply Jikkou Topics and ACLs

on:
  push:
    branches: [main]
    paths:
      - 'topics/**'

jobs:
  jikkou:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Jikkou
        run: |
          jikkou apply --files topics/*.yaml
